w-1=/home/alex/.config/wallpapers/LimeFrenzy/13.jpg
w-2=/home/alex/.config/wallpapers/LimeFrenzy/13.jpg
w-3=/home/alex/.config/wallpapers/Crimson-Blue/sun-set.jpg
w-4=/home/alex/.config/wallpapers/Crimson-Blue/sun-set.jpg
w-5=/home/alex/.config/wallpapers/Decay-Green/aurora_borealis.png
w-6=/home/alex/.config/wallpapers/Decay-Green/moments_before_desk.png
w-7=/home/alex/.config/wallpapers/aurora.png
w-8=/home/alex/.config/wallpapers/Crimson-Blue/boat.jpg
w-9=/home/alex/.config/wallpapers/Nature/wallhaven_qr27rq.jpg
w-10=/home/alex/.config/wallpapers/aesthetic_deer.png
