context.modules = [
    {
        name = libpipewire-module-filter-chain
        args = {
            node.description = "Noise Canceling Source"
            media.name = "Noise Canceling Source"
            filter.graph = {
                nodes = [
                    {
                        type = ladspa
                        name = rnnoise
                        plugin = /usr/lib/ladspa/librnnoise_ladspa.so
                        label = noise_suppressor_mono
                        control = {
                            "VAD Threshold (%)" 50.0
                            "VAD Grace Period (ms)" 200
                        }
                    }
                ]
            }
            capture.props = {
                node.name = "capture.rnnoise_source"
                node.passive = true
                audio.rate = 48000
                target.object = "alsa_input.pci-0000_06_00.6.pro-input-0"
            }
            playback.props = {
                node.name = "rnnoise_source"
                media.class = "Audio/Source"
                audio.rate = 48000
            }
        }
    }
    {
        name = libpipewire-module-filter-chain
        args = {
            node.description = "Noise Canceling Source (BT)"
            media.name = "Noise Canceling Source (BT)"
            filter.graph = {
                nodes = [
                    {
                        type = ladspa
                        name = rnnoise
                        plugin = /usr/lib/ladspa/librnnoise_ladspa.so
                        label = noise_suppressor_mono
                        control = {
                            "VAD Threshold (%)" 50.0
                            "VAD Grace Period (ms)" 200
                        }
                    }
                ]
            }
            capture.props = {
                node.name = "capture.rnnoise_source_bt"
                node.passive = true
                audio.rate = 48000
                node.autoconnect = false
                node.linger = true
            }
            playback.props = {
                node.name = "rnnoise_source_bt"
                media.class = "Audio/Source"
                audio.rate = 48000
            }
        }
    }
]
